name: CI

on: [push]
env:
  ROS_DISTRO: melodic

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        cd ros_ws/
        cp toad.example toad.settings
        sed -i -e 's/CONFIGURED="0"/CONFIGURED="1"/g' toad.settings
        ./toad.sh init system ci
        ./toad.sh init ros ci
    - name: Run Tests
      run: |
        source /opt/ros/${ROS_DISTRO}/setup.bash
        catkin_make run_tests && catkin_tes_results
