name: CI

on: [push]

jobs:
  build_melodic:
    runs-on: ubuntu-18.04
    env:
      ROS_DISTRO: melodic
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        cd ros_ws/
        cp toad.example toad.settings
        sed -i -e "s/melodic/${ROS_DISTRO}/g" toad.settings
        sed -i -e 's/CONFIGURED="0"/CONFIGURED="1"/g' toad.settings
        ./toad.sh init system ci
        ./toad.sh init ros ci
    - name: Run Tests
      run: |
        source /opt/ros/${ROS_DISTRO}/setup.bash
        catkin_make run_tests && catkin_tes_results
  build_kinetic:
    runs-on: ubuntu-16.04
    env:
      ROS_DISTRO: kinetic 
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        cd ros_ws/
        cp toad.example toad.settings
        sed -i -e "s/melodic/${ROS_DISTRO}/g" toad.settings
        sed -i -e 's/CONFIGURED="0"/CONFIGURED="1"/g' toad.settings
        ./toad.sh init system ci
        ./toad.sh init ros ci
    - name: Run Tests
      run: |
        source /opt/ros/${ROS_DISTRO}/setup.bash
        catkin_make run_tests && catkin_tes_results
