name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        cd ros_ws/
        cp toad.example toad.settings
        sed -i -e 's/CONFIGURED="0"/CONFIGURED="1"/g' toad.settings
        ./toad.sh init system
        ./toad.sh init ros
